version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules   
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # 解决 Docker 热更新问题（React）

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload
